version: '2.4'

services:
  web:
    image: parth7091/next-web-app:latest
    environment:
      - MONGO_URI=${{ secrets.MONGO_URI }}
    volumes:
     - ./app-data:/app
    ports:
      - 3000:3000
volumes:
  app-data: {}