name: Deploy Next-JS-Web-App

on:
  push:
    branches:
      - main

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Images
        run: |
          docker build -t parth7091/next-web-app .
      - name: Publish Images to Docker Hub
        run: |
          docker push parth7091/next-web-app:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull images from Docker Hub
        run: |
          docker pull parth7091/next-web-app:latest
      - name: Run Docker Conainer
        run: |
          docker run -d -p 3000:3000 --name next-web-app-container -e MONGODB_URI:'${{ secrets.MONGO_URI }}' parth7091/next-web-app
    #   - name: Run Docker Containers
    #     run: |
    #       cd /data/next-js-admin-dashboard
    #       docker-compose up -d
      # # - name: Remove old containers
      # #   run: |
      # #     docker-compose down --remove-orphans
      # - name: Run Docker Containers
      #   run: docker-compose up -d





# name: Deploy Next-JS-Web-App

# on:
#   push:
#     branches:
#       - main

# env:
#   MONGO_URI: ${{ secrets.MONGO_URI }}

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Source
#         uses: actions/checkout@v4
#       - name: Login to Docker Hub
#         run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
#       - name: Build Docker Images
#         run: |
#           docker build -t parth7091/next-web-app .
#       - name: Publish Images to Docker Hub
#         run: |
#           docker push parth7091/next-web-app:latest
#   deploy:
#     needs: build
#     runs-on: self-hosted
#     steps:
#       - name: Pull images from Docker Hub
#         run: |
#           docker pull parth7091/next-web-app:latest
#       - name: Copy files from _temp folder
#         run: |
#           cp -r /home/ubuntu/actions-runner-next/_work/_temp/* /data/next-web-app
#           ls -l /data/next-web-app
#           rm -rf /home/ubuntu/actions-runner/_work/_temp/* 
#       - name: Run Docker Containers
#         run: |
#           cd /data/next-js-admin-dashboard
#           docker-compose up -d
#       - name: Remove old containers
#         run: |
#           docker-compose down --remove-orphans
#       - name: Run Docker Containers
#         run: docker-compose up -d
